name: Format

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  format-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install Black
        run: pip install black

      - name: Format code with Black
        run: black .

      - name: Push changes
        if: success() && github.event_name == 'push'
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Apply Black formatting"
          git push
